// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeCVnwUNW-wiBHM_n5lp3D8b6qZuRlKT4',
    appId: '1:615088208953:web:292a9ded2f2174087de1e8',
    messagingSenderId: '615088208953',
    projectId: 'login-d2344',
    authDomain: 'login-d2344.firebaseapp.com',
    storageBucket: 'login-d2344.firebasestorage.app',
    measurementId: 'G-G2SR1BTEHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-usqYZzhkAVpQzLuMG0_rUmXU24lj-oo',
    appId: '1:615088208953:android:6ea9dc88b7d68f757de1e8',
    messagingSenderId: '615088208953',
    projectId: 'login-d2344',
    storageBucket: 'login-d2344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQkcLGs3CevUGtZmPUPMll8sLwL1V8nM',
    appId: '1:615088208953:ios:c96929e0dc598adb7de1e8',
    messagingSenderId: '615088208953',
    projectId: 'login-d2344',
    storageBucket: 'login-d2344.firebasestorage.app',
    iosBundleId: 'com.example.plantillalogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQkcLGs3CevUGtZmPUPMll8sLwL1V8nM',
    appId: '1:615088208953:ios:c96929e0dc598adb7de1e8',
    messagingSenderId: '615088208953',
    projectId: 'login-d2344',
    storageBucket: 'login-d2344.firebasestorage.app',
    iosBundleId: 'com.example.plantillalogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeCVnwUNW-wiBHM_n5lp3D8b6qZuRlKT4',
    appId: '1:615088208953:web:8347963c8ccda2657de1e8',
    messagingSenderId: '615088208953',
    projectId: 'login-d2344',
    authDomain: 'login-d2344.firebaseapp.com',
    storageBucket: 'login-d2344.firebasestorage.app',
    measurementId: 'G-YPVGX0VSKQ',
  );
}
